name: 保活
on:
  schedule:
    - cron: '0 0 1,20 * *'
permissions:
  actions: write
jobs:
  cronjob-based-github-action:
    name: 保活
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: gautamkrishnar/keepalive-workflow@v2
        with:
          commit_message: 空提交保活
          committer_username: roiding
          committer_email: maodoulove19950815@gmail.com
          workflow_files: monitor.yml