name: 保活
on:
  schedule:
    - cron: '0 0 1 * *'
permissions:
  actions: write
jobs:
  cronjob-based-github-action:
    name: 保活
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: gautamkrishnar/keepalive-workflow@v2